-- ════════════════════════════════════════════════════════════════════════
-- Migration 003 (v0.2) — Cross-module
-- Module: payroll (영향: logistics)
-- 목적: work_log_source ENUM 에 'DELIVERY' 값 안전 추가 (이미 있으면 skip)
-- 룰: EP-100 (work_log) / EL-040 (logistics 이벤트 발행)
-- ════════════════════════════════════════════════════════════════════════
--
-- 배경:
-- - logistics 의 delivery.md (EL-040) — DELIVERY_COMPLETED 이벤트 → payroll WorkLog
-- - payroll 의 work_log.md 는 source_type='DELIVERY' 명시 사용
-- - payroll v0.10 / v0.11 마이그레이션 이력에 DELIVERY 추가 명시 X
-- - 안전 처리 — 이미 있으면 skip, 없으면 추가 (IF NOT EXISTS)
--
-- 적용 순서: DB → application deploy
-- 롤백: ENUM 값 제거 불가. 데이터 보존 + 별도 마이그레이션.
-- ════════════════════════════════════════════════════════════════════════

-- 정확한 위치 (ATTENDANCE 후, MANUAL 전 등) 는 v0.10 정의에 따라 결정.
-- 안전: AFTER 명시 X — PostgreSQL 이 적절한 위치 결정.
ALTER TYPE work_log_source ADD VALUE IF NOT EXISTS 'DELIVERY';

-- 검증 쿼리 (마이그레이션 후)
-- SELECT enum_range(NULL::work_log_source);
-- 기대: DELIVERY 가 enum 에 존재. 없었으면 새로 추가됨.

-- ════════════════════════════════════════════════════════════════════════
-- 영향 받는 룰 / 코드 (Phase 1 구현 시):
-- 1. payroll/rules/work_log.md:
--    - EP-100 source_type 표에 DELIVERY 명시 (이미 작성됨, 검증)
--    - source_id 형식: deliveryId (logistics_deliveries.id)
--    - 자동 생성 트리거: DELIVERY_COMPLETED 이벤트
-- 2. logistics/rules/delivery.md:
--    - EL-045 영향 매트릭스 — DELIVERY_COMPLETED → payroll work_log
-- 3. business/payroll/handlers/delivery-completed-handler.ts (Phase 1+):
--    - 멱등 처리 (processed_events + UNIQUE)
--    - 기사 compensation_settings 기반 amount 산출:
--        * per_delivery: 고정 금액 × 1
--        * per_distance: km × 단가
--        * per_time: 분 × 단가
--    - WorkLog INSERT (source_type='DELIVERY', source_id=deliveryId)
-- 4. payroll work_log_source 기존 값 (참고):
--    - ATTENDANCE / MANUAL / ADJUSTMENT / PIECEWORK (v0.11 추가)
--    - DELIVERY 추가 (v0.2)
-- ════════════════════════════════════════════════════════════════════════
